version: '3.8'

services:
  medclinik-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medclinik-backend
    restart: always
    ports:
      - "3010:3006"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
