version: '3.8'

services:
  medclinik-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medclinik-backend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.medclinik.entrypoints=websecure"
      - "traefik.http.routers.medclinik.rule=Host(`medclinik.backnd-api.cloud`)"
      - "traefik.http.routers.medclinik.tls.certresolver=letsencrypt"
      - "traefik.http.services.medclinik.loadbalancer.server.port=3006"
    ports:
      - "3010:3006"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://medclinik_user:medclinik_password@medclinik-db:5432/medclinik_db?schema=public
    depends_on:
      - medclinik-db

  medclinik-db:
    image: postgres:14
    container_name: medclinik-db
    restart: always
    environment:
      POSTGRES_USER: medclinik_user
      POSTGRES_PASSWORD: medclinik_password
      POSTGRES_DB: medclinik_db
    ports:
      - "5434:5432"
    volumes:
      - medclinik_postgres_data:/var/lib/postgresql/data

volumes:
  medclinik_postgres_data:
